### ISSUE TITLE
Keeps adding new line before block comment

### ISSUE THREAD

**Issue by Andikki** [tierratelematics/code-beautifier#11]
If you set preserve_newlines in options, it keeps adding a new line before a comment block, if this comment block is between rules.

settings.json:
```json
"beautify.options": {
    "preserve_newlines": true
},
```

Initial css:
```css
.some-rule {
  width: 20px;
}

/* Description for the next rules */
.other-rule {
  /* width: 40%; */
  width: 20px;
}

```

After a few beautifies:
```css
.some-rule {
  width: 20px;
}







/* Description for the next rules */

.other-rule {
  /* width: 40%; */
  width: 20px;
}
```
