### ISSUE TITLE
Sass List After formatting

### ISSUE THREAD

**Issue by Cyclone77** [tierratelematics/code-beautifier#5]
**After formatting**
``` scss
$animal-data: (puma,
black,
default),
(sea-slug,
blue,
pointer),
(egret,
white,
move);
@each $animal,
$color,
$cursor in $animal-data {
    .#{$animal}-icon {
        background-image: url('/images/#{$animal}.png');
        border: 2px solid $color;
        cursor: $cursor;
    }
}
```
